# Generated by Django 2.0.6 on 2019-01-04 04:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('security', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=50)),
                ('stocks_own', models.IntegerField(null=True)),
                ('providers_name', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('csv_file', models.CharField(max_length=50, null=True)),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('security', models.CharField(max_length=50)),
                ('securities_tested', models.PositiveIntegerField(null=True)),
                ('strategy', django.contrib.postgres.fields.jsonb.JSONField()),
                ('percentage_up', models.FloatField(default=None)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('max_point', models.FloatField(null=True)),
                ('min_point', models.FloatField(null=True)),
                ('trades', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='securities',
            name='best_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShowIndicators.Strategies'),
        ),
    ]
