# Generated by Django 2.0.6 on 2018-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategies',
            name='trades',
            field=models.IntegerField(null=True),
        ),
    ]
