# Generated by Django 2.0.6 on 2018-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0002_strategies_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
