# Generated by Django 2.0.6 on 2018-09-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0003_auto_20180902_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
