# Generated by Django 2.0.6 on 2018-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0004_auto_20180903_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='securities',
            name='csv_file',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securities',
            name='last_update',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
