# Generated by Django 2.0.6 on 2018-11-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0005_auto_20180903_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='securities',
            name='stocks_own',
            field=models.IntegerField(null=True),
        ),
    ]
