# Generated by Django 2.0.6 on 2018-07-18 03:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('market', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowIndicators.Securities')),
            ],
        ),
    ]
