# Generated by Django 2.0.6 on 2018-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategies',
            name='percentage_up',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='strategies',
            name='security',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
