# Generated by Django 2.0.6 on 2018-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowIndicators', '0003_auto_20180722_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategies',
            name='security',
            field=models.CharField(max_length=50),
        ),
    ]
